baseURL: https://trusting-noether-9de36b.netlify.com/
languageCode: en-us
title: EzyEnglish
theme: vanilla-bootstrap-hugo-theme
googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Learn
    pre: book
    url: / english-speaking/
  - name: Blog
    pre: file
    url: /post/
    weight: 2
  - name: Resources
    pre: book
    url: /resources/
    weight: 3
  - name: About
    pre: smile
    url: /about/
    weight: 4
 # - name: RSS
 #   pre: rss
 #   url: /index.xml
 #   weight: 5
 

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Speak English Fluently with Our FREE Basic English Speaking Lessons. We will use very simple phrases and expressions to help you with your English speaking.
  footerText: © 2020 Bakari Mustafa
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
